improve easymotions and others stuffs

diff --git a/.aliases/bash-functions b/.aliases/bash-functions
--- a/.aliases/bash-functions
+++ b/.aliases/bash-functions
@@ -58,9 +58,35 @@ run-nice-keyboard() {
     tmux
 }
 
+run-nice-keyboard-console() {
+# You have to be root to remap the console keyboard.
+if [ "$(id -u)" != "0" ]; then
+    echo "This script is not running as root so"
+    echo "the console CapsLock cannot be remapped."
+    echo "Perhaps you forgot to run this under sudo."
+    echo "Note that this problem does not effect X."
+    echo "This only effects the consoles running on"
+    echo "Alt-f1 through Alt-f6."
+    exit 2
+fi
+
+# Remap the CapsLock key to a Control key for the console.
+(dumpkeys | grep keymaps; echo "keycode 58 = Control") | loadkeys
+
+}
+
 # copy to graphic clipboard
 copy() {
     xclip -selection clipboard $1
+}
+
+# video clipper, requires avconv package
+# usage:
+# $ corte input.ext daqui paca output.ext
+# daqui formmat: hh:mm:ss
+# paca formmat: hh:mm:ss
+corte() {
+    avconv -i $1 -vcodec copy -acodec copy -ss $2 -t $3 $4
 }
 
 runflux() {
